# Generated by Django 2.0 on 2017-12-30 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 3, 1, 44, 171951, tzinfo=utc)),
        ),
    ]
